version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:

  db:
    image: postgres:13.10
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file:
      - .env

  backend:
    image: angolovanov/foot_backend
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    image: angolovanov/foot_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static

  nginx:
    image: angolovanov/foot_nginx
    ports:
      - 7070:80
    depends_on:
      - frontend
    volumes:
      - static:/static
      - media:/app/media
      - /docs/:/usr/share/nginx/html/api/docs/
